name = "mdv5a_fp16"
path = "models/md_v5a_d_pp_fp16.onnx"
url = "https://megascops.app/models/md_v5a_d_pp_fp16.onnx"
imgsz = 1280
classes = ["Animal", "Person", "Vehicle"]
md5 = "7df84e4900ac2eaabd91a49e56e21bc3"
